// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://troqkvnbdmovkxbthqan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyb3Frdm5iZG1vdmt4YnRocWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTEyNzcsImV4cCI6MjA3NDI2NzI3N30.-eqfHwhYBu6289Vtvh-blIUH_-33biFLvuldaoNei00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});